### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by cbordeman** [RandomShaper/vs-high-contrast-hack#2]
Can this be updated to work for 2019?

**Comment by RandomShaper** [comment]
For me this is not needed anymore now Windows has a dark mode for Explorer. Therefore, I need no longer to use a high contrast theme to emulate OS-wide dark mode.

I'd research how to do it on VS 2019, but unfortunately I'm too busy. I'm sorry.

If anyone is interested and makes a PR with it, I'd gladly merge it.

**Comment by cbordeman** [comment]
> For me this is not needed anymore now Windows has a dark mode for Explorer. Therefore, I need no longer to use a high contrast theme to emulate OS-wide dark mode.
> 
> I'd research how to do it on VS 2019, but unfortunately I'm too busy. I'm sorry.
> 
> If anyone is interested and makes a PR with it, I'd gladly merge it.

Explorer is not the only thing in Windows.  Virtually every other window is still white and unreadable by the rest of us with extremely low eyesight.
